version: '3.8'

services:
    adminer:
        image: adminer
        restart: on-failure
        ports:
            - '8080:8080'
    nginx:
        image: nginx:1.19.0-alpine
        restart: on-failure
        volumes:
            - './apps/xml_array_return/public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '80:80'
        depends_on: 
            - php
    php:
        build:
            context: './'
            dockerfile: docker/php/Dockerfile
        volumes:
            - './apps/xml_array_return/:/usr/src/app'
        restart: on-failure
        env_file:
            - .env
        user: 1000:1000
    