<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVvkpxnn\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVvkpxnn/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVvkpxnn.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVvkpxnn\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerVvkpxnn\srcDevDebugProjectContainer([
    'container.build_hash' => 'Vvkpxnn',
    'container.build_id' => '015ab6c9',
    'container.build_time' => 1607449575,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVvkpxnn');
